name: Pruebas Automatizadas Selenium
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar servidor demo en segundo plano
        run: nohup npm start &

      - name: Esperar a que el servidor arranque
        run: sleep 2

      - name: Correr pruebas en modo headless
        run: npm run test:headless
